spring:
    application:
      name: hub-api
    profiles:
      active: ${SPRING_PROFILES_ACTIVE}
security:
  jwt:
    token:
      secret-key: ${JWT-SECRET-KEY}
      expire-length: ${JWT-EXPIRE-LENGTH}
      
