# ao abrir uma pr em direção a hom, o workflow vai testar o codigo que originou a pr
name: PR to homologation environment
on:
  pull_request:
    types: opened
    branches: 
        - hom
jobs:
    tbd:
        runs-on: ubuntu-latest
        steps:
          - name: tbd
            run: echo 'Oi'