# ao abrir fazer um push em direção a hom, 
# o workflow vai fazer o deploy do app para server de homologação (render)
name: Push to homologation environment
on:
  push:
    branches: 
        - hom
jobs:
    tbd:
        runs-on: ubuntu-latest