# finalidade: rodar testes quando uma pr for aberta em direção a hom ou dev
name: Run tests bases on environment
on:
  pull_request:
    types: opened
    branches:
      - hom
      - dev
jobs:
  run-dev:
    if: github.event.pull_request.base.ref == 'dev'
    uses: astra-software/hub-back/.github/workflows/test-dev.yml@main
  run-hom:
    if: github.event.pull_request.base.ref == 'hom'
    uses: astra-software/hub-back/.github/workflows/test-hom.yml@main