# finalidade: rodar testes quando uma pr for aberta em direção a hom ou dev
name: Run tests bases on environment
on:
  pull_request:
    types: opened
    branches:
      - hom
      - dev
jobs:
  run-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev'
    steps:
      - name: Run development environment tests
        uses: ./.github/workflows/test-dev.yml
  run-hom:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'hom'
    steps:
      - name: Run homologation environment tests
        uses: ./.github/workflows/test-hom.yml