name: Tests in homologation
on: workflow_call
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        container: 
            image: maven:3.9.9-eclipse-temurin-21-alpine
            env:
                POSTGRE_URL_HOM: ${{ secrets.POSTGRE_URL_HOM }}
                POSTGRE_USER_HOM: ${{ secrets.POSTGRE_USER_HOM }}
                POSTGRE_PASSWORD_HOM: ${{ secrets.POSTGRE_PASSWORD_HOM }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache dependency
              uses: actions/cache@v4
              with:
                path: ~/.m2
                key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    maven-${{ runner.os }}
            - name: Install dependencies and test
              run: mvn clean test -Dspring.profiles.active=hom